### ISSUE TITLE
Add support for 'on{Event}' notation

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/ewc#42]
I edited DemoPassword and changed line [41] by adding an event handler:
````
(uAppW,'∆pP1.B31001')eWC('Type' 'Edit')('Posn' 120 112)('Size' 16 120)('Style' 'Single')('Border' 0)('VScroll' 0)('HScroll' ¯1)('FontObj' 'FntSys')('FCol'(2⊃GetColor'Edit'))('Tip' 'B31001')('MaxLength' 18)('Password' '*')('EdgeStyle' 'Ridge')('Event' 'onChange' 'onChangePswd')
 ````

This led to an error when I opened the page:

````
 22:19.735 U:  Unsupported event setting at  DemoPassword[41]  CBRunDemo[24]  processEvent[68]
 22:19.736 U:           onChange  onChangePswd
51:LENGTH ERROR
fixUpProps[14] values[ix]←normaliseEvents values[ix]
                         ∧
      ≢normaliseEvents values[ix]
0
       values[ix]
┌───────────────────────┐
│┌────────┬────────────┐│
││onChange│onChangePswd││
│└────────┴────────────┘│
└───────────────────────┘
````
Using `('Event' 'Change'...` fixed the problem - but I think that (according to my understanding of https://help.dyalog.com/19.0/#GUI/Properties/Event.htm)  `onEvent` should also be supported.

I later noticed that there also is code which sets a `Change` handler for this field and others at a later point, so I changed my approach - but this is noteworthy anyway, I think.

**Comment by mkromberg** [comment]
Completed.
